name: Auto Resolve Merge Conflicts for Specific Files

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  resolve_conflicts:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the pull request
      - name: Checkout the pull request
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}  # Check out the PR branch